// layout.tsx

import './globals.css'

import type { Metadata } from 'next'
import { Bricolage_Grotesque } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const bricolageGrotesque = Bricolage_Grotesque({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${bricolageGrotesque.className}`}>
        {children}
      </body>
    </html>
  )
}
